version: '3.1'

services:

  db:
    image: mariadb:10.4.12
    build: 
      context: ./db
      args:
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    container_name: "${MYSQL_CONTAINER}"
    restart: unless-stopped
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./db/mysql:/var/lib/mysql

  web:
    image: php:7.3-apache
    build: ./php
    container_name: "${HTTP_CONTAINER}"
    restart: unless-stopped
    environment:
      TZ: Europe/Rome
      db_host: "${MYSQL_CONTAINER}"
      db_username: "${MYSQL_USER}"
      db_password: "${MYSQL_PASSWORD}"
      db_db_name: "${IUB_DB_NAME}"
      db_db_port: 3306
      db_encryption_key: "${IUB_ENCRYPTION_KEY}"
      personalServer_host: "${IUB_REPOSITORY_HOST}"
      personalServer_username: "${IUB_REPOSITORY_USERNAME}"
      personalServer_password: "${IUB_REPOSITORY_PASSWORD}"
      http_version: "${IUB_SOFTWARE_VERSION}"
      http_production: "${IUB_PRODUCTION}"
      http_proxy_ip: "${IUB_PROXY_IP}"
      http_proxy_port: "${IUB_PROXY_PORT}"
      imgur_client_id: "${IUB_IMGUR_ID}"
      imgur_client_secret: "${IUB_IMGUR_SECRET}"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./site:/var/www/html
    ports:
      - ${HTTP_PORT}:80
