version: '3.1'

services:

  db:
    image: mariadb:latest
    build: 
      context: ./db
      args:
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    container_name: IUB_sql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
  #    - ./db/sql_files:/docker-entrypoint-initdb.d
      - ./db/mysql:/var/lib/mysql

  web:
    image: php:7.3.13-apache
    build: ./php
    container_name: IUB_php
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./site:/var/www/html
    ports:
      - ${HTTP_PORT}:80  # expose container's port 80 on host's port 8080, the web service
