FROM mariadb:latest
ARG MYSQL_ROOT_PASSWORD
#RUN  /etc/init.d/mysql start
RUN echo "ROOT_PSW: ${MYSQL_ROOT_PASSWORD}"
#RUN  mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE lbasadasda" 

#GRANT Create ON *.* TO 'IUB_user'@'%';
#GRANT Create view ON *.* TO 'IUB_user'@'%';
#GRANT Index ON *.* TO 'IUB_user'@'%';
#FLUSH PRIVILEGES;
